apiVersion: v2
name: feedbacksystem
description: A Helm chart for Kubernetes
type: application
version: 0.3.0
appVersion: 1.4.0
dependencies:
  - name: mysql
    version: 9.4.1
    repository: 'https://charts.bitnami.com/bitnami'
    condition: core.enabled
  - name: minio
    version: 11.10.12
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
  - name: postgresql
    version: 12.0.0
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
    alias: runnerPostgres
  - name: mysql
    version: 9.4.1
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
    alias: runnerMysql
  - name: mongodb
    version: 13.3.0
    repository: 'https://charts.bitnami.com/bitnami'
    condition: sqlChecker.enabled
    alias: checkerMongodb
  - name: postgresql
    version: 12.0.0
    repository: 'https://charts.bitnami.com/bitnami'
    condition: runner.enabled
    alias: runnerPlaygroundPostgres
