common:
  config:
    protocol: "https:"
    hostname: feedback.example.org
    port: 443

core:
  enabled: true
  image:
    registry: docker.io
    name: thmmniii/fbs-core
    tag: "v1.1.1"
  volumes:
    config:
      size: "8G"
      mode: "ReadWriteOnce"
    uploadDir:
      size: "16G"
      mode: "ReadWriteOnce"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "250Mi"
      limit: "4Gi"
  config:
    jwtSecret: "2edb8793d987389e1626918e0ec1dbee" # CHANGE ME
  ingress:
    enabled: true

runner:
  enabled: true
  image:
    registry: docker.io
    name: thmmniii/fbs-runner
    tag: "v1.1.1"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "250Mi"
      limit: "4Gi"
  dink:
    image:
      registry: docker.io
      name: library/docker
      tag: "20.10.21-dind"
    resources:
      cpu:
        request: 0.1
        limit: 2
      memory:
        request: "100Mi"
        limit: "4Gi"

sqlChecker:
  enabled: true

digitalClassroom:
  enabled: true
  image:
    registry: ghcr.io
    name: thm-mni-ii/digital-classroom
    tag: "v1.0.1"
  resources:
    cpu:
      request: 0.1
      limit: 2
    memory:
      request: "250Mi"
      limit: "4Gi"
  config:
    jwtSecret: "2edb8793d987389e1626918e0ec1dbee" # CHANGE ME
    secret: "1f2a08f5dbd81580a6fb0f645dce3737"
    bbb:
      url: "https://bbb.example.org"
      secret: 1234

mysql:
  auth:
    database: fbs
    username: fbs
    password: fbs # CHANGE ME
    rootPassword: root # CHANGE ME
    createDatabase: true
  primray:
    existingConfigmap: 'CHANGE-ME'

runnerMysql:
  nameOverride: runner-mysql
  auth:
    database: fbs
    username: fbs
    password: fbs # CHANGE ME
    rootPassword: root # CHANGE ME

runnerPostgres:
  nameOverride: runner-postgres
  auth:
    database: fbs
    username: fbs
    password: fbs # CHANGE ME
    postgresPassword: root # CHANGE ME

checkerMongodb:
  nameOverride: checker-mongodb
  auth:
    database: fbs
    username: fbs
    password: fbs # CHANGE ME
    rootPassword: root # CHANGE ME

minio:
  auth:
    rootPassword: fbs
