'fbs-core: web':
  - changed-files:
      - any-glob-to-any-file: 'modules/fbs-core/web/**'

'fbs-core: api':
  - changed-files:
      - any-glob-to-any-file:
          - 'modules/fbs-core/api/**'
          - 'modules/fbs-core/math-parser/**'
          - 'runtime-images/**'
          - 'scripts/ci/**'
          - 'docker-compose*.yml'
          - 'Dockerfile'

'fbs-eat':
  - changed-files:
      - any-glob-to-any-file: 'modules/fbs-eat/**'

'fbs-runner: checker':
  - changed-files:
      - any-glob-to-any-file: 'modules/fbs-runner/**'

'checker: excel':
  - changed-files:
      - any-glob-to-any-file: 'modules/fbs-core/api/**/excel/**'

'checker: math':
  - changed-files:
      - any-glob-to-any-file: 'modules/fbs-core/math-parser/**'

'checker: sql':
  - changed-files:
      - any-glob-to-any-file: 'modules/fbs-sql-checker/**'

'Docker':
  - changed-files:
      - any-glob-to-any-file:
          - 'docker-compose*.yml'
          - 'Dockerfile'

'CI/CD':
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - 'scripts/ci/**'
