version: '3'

services:
  test-mysql:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: twRuvi2ejllDdA4nnQLa08O
      MYSQL_DATABASE: fbs
    ports:
      - 127.0.0.1:3306:3306
  minio:
    image: minio/minio:RELEASE.2022-10-29T06-21-33Z
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - ./data/minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: SqfyBWhiFGr7FK60cVR2rel
    command: server --console-address ":9001" /data
    restart: unless-stopped
