version: '3'

services:
  mysql1:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: twRuvi2ejllDdA4nnQLa08O
      MYSQL_DATABASE: fbs
    volumes:
      - ./data/mysql1:/var/lib/mysql
    ports:
      - "3306:3306"

  bashenv:
    build: bash
  nodeenv:
    build: node-container

  mysql2:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SqfyBWhiFGr7FK60cVR2rel
    volumes:
      - ./data/mysql2:/var/lib/mysql

  ws:
    build: ws
    restart: always
    depends_on:
      - mysql1
      - kafka1
      - zoo1
    ports:
      - "443:443"
    volumes:
      - ./data/upload-dir:/upload-dir
      - ./conf/ws:/usr/local/ws/conf
    environment:
      #- KEYSTORE_PATH=file:/usr/local/ws/conf/feedback.p12
      - SERVER_HOST=https://localhost
      - KAFKA_ADDRESS=kafka1:9092
      - MYSQL_URI=jdbc:mysql://mysql1:3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=twRuvi2ejllDdA4nnQLa08O
      - JITSI_URI=https://fk-conf.mni.thm.de/newConf/rooms.php
      - JITSI_SECRET=8Dsupersecurekeydf0
      - JITSI_USER=fbs
      - JWT_SECRET=8Dsupersecurekeydf0
      - BBB_SECRET

  sqlchecker:
    build: sql-checker
    depends_on:
      - mysql2
      - kafka1
      - zoo1
      - ws
    environment:
      KAFKA_ADDRESS: kafka1:9092
      MYSQL_URI: jdbc:mysql://mysql2:3306
      MYSQL_USER: root
      MYSQL_PASSWORD: SqfyBWhiFGr7FK60cVR2rel
    volumes:
      - ./data/upload-dir:/upload-dir

  master-runner:
    build: master-runner
    ports:
      - "8081:8081"
    environment:
      BASH_DOCKER: "thmmniii/bashenv:dev-latest"
      HOST_TMP_DIR: "/tmp/feebi" # Need to be the same folder as mounted to /dockertemp
      INSIDE_DOCKER: "true"
    volumes:
      - /tmp/feebi:/dockertemp # A temp dir where docker image stores task submissions temporarily
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/upload-dir:/upload-dir


