{{ if .Values.sqlChecker.enabled }}
apiVersion: v1
kind: ConfigMap
type: Opaque
metadata:
  name: {{ .Release.Name }}-sql-checker
data:
  mongoDatabase: {{ .Values.checkerMongodb.auth.database }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-sql-checker
data:
  mongodbUri: {{ print "mongodb://" .Values.checkerMongodb.auth.username ":" .Values.checkerMongodb.auth.passwords "@" .Release.Name "-checkerMongodb" ":27017" | b64enc }}
{{ end }}
