import { CheckerConfig } from "../model/CheckerConfig";

export const CHECKERCONFIG: CheckerConfig[] = [{"id":1,"checkerType":"video/quicktime","mainFileUploaded":true,"secondaryFileUploaded":false,"ord":"iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut"},
  {"id":2,"checkerType":"application/x-troff-msvideo","mainFileUploaded":true,"secondaryFileUploaded":true,"ord":"justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus"},
  {"id":3,"checkerType":"video/msvideo","mainFileUploaded":true,"secondaryFileUploaded":true,"ord":"parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa"},
  {"id":4,"checkerType":"video/quicktime","mainFileUploaded":false,"secondaryFileUploaded":true,"ord":"integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent"},
  {"id":5,"checkerType":"image/gif","mainFileUploaded":true,"secondaryFileUploaded":true,"ord":"nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis"},
  {"id":6,"checkerType":"text/plain","mainFileUploaded":false,"secondaryFileUploaded":true,"ord":"morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui"},
  {"id":7,"checkerType":"application/pdf","mainFileUploaded":true,"secondaryFileUploaded":false,"ord":"turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec"},
  {"id":8,"checkerType":"image/tiff","mainFileUploaded":true,"secondaryFileUploaded":false,"ord":"ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra"},
  {"id":9,"checkerType":"image/png","mainFileUploaded":true,"secondaryFileUploaded":false,"ord":"donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam"},
  {"id":10,"checkerType":"application/vnd.ms-powerpoint","mainFileUploaded":false,"secondaryFileUploaded":true,"ord":"iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus"},
  {"id":11,"checkerType":"image/gif","mainFileUploaded":true,"secondaryFileUploaded":true,"ord":"quam pede lobortis ligula sit amet eleifend pede libero quis"},
  {"id":12,"checkerType":"image/x-tiff","mainFileUploaded":false,"secondaryFileUploaded":true,"ord":"vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis"},
  {"id":13,"checkerType":"application/msword","mainFileUploaded":false,"secondaryFileUploaded":true,"ord":"eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam"},
  {"id":14,"checkerType":"image/gif","mainFileUploaded":false,"secondaryFileUploaded":true,"ord":"cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum"},
  {"id":15,"checkerType":"application/x-excel","mainFileUploaded":false,"secondaryFileUploaded":false,"ord":"donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque"},
  {"id":16,"checkerType":"video/mpeg","mainFileUploaded":true,"secondaryFileUploaded":false,"ord":"cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac"},
  {"id":17,"checkerType":"image/gif","mainFileUploaded":true,"secondaryFileUploaded":true,"ord":"hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec"},
  {"id":18,"checkerType":"image/tiff","mainFileUploaded":false,"secondaryFileUploaded":false,"ord":"rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis"},
  {"id":19,"checkerType":"video/msvideo","mainFileUploaded":false,"secondaryFileUploaded":true,"ord":"duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a"},
  {"id":20,"checkerType":"image/png","mainFileUploaded":true,"secondaryFileUploaded":false,"ord":"sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at"},
  {"id":21,"checkerType":"application/excel","mainFileUploaded":false,"secondaryFileUploaded":false,"ord":"habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida"},
  {"id":22,"checkerType":"application/x-excel","mainFileUploaded":false,"secondaryFileUploaded":false,"ord":"sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere"},
  {"id":23,"checkerType":"image/gif","mainFileUploaded":false,"secondaryFileUploaded":false,"ord":"eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat"},
  {"id":24,"checkerType":"application/excel","mainFileUploaded":false,"secondaryFileUploaded":false,"ord":"laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel"},
  {"id":25,"checkerType":"audio/x-mpeg-3","mainFileUploaded":true,"secondaryFileUploaded":true,"ord":"justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices"},
  {"id":26,"checkerType":"application/mspowerpoint","mainFileUploaded":false,"secondaryFileUploaded":true,"ord":"suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis"},
  {"id":27,"checkerType":"application/x-excel","mainFileUploaded":true,"secondaryFileUploaded":true,"ord":"nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum"},
  {"id":28,"checkerType":"application/vnd.ms-excel","mainFileUploaded":true,"secondaryFileUploaded":true,"ord":"vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo"},
  {"id":29,"checkerType":"application/x-troff-msvideo","mainFileUploaded":false,"secondaryFileUploaded":false,"ord":"euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam"},
  {"id":30,"checkerType":"application/x-msexcel","mainFileUploaded":true,"secondaryFileUploaded":true,"ord":"integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed"}]
