-- MySQL Script generated by MySQL Workbench
-- Fri Aug 14 12:09:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fbs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fbs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fbs` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `fbs` ;

-- -----------------------------------------------------
-- Table `fbs`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fbs`.`course` ;

CREATE TABLE IF NOT EXISTS `fbs`.`course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(100) NOT NULL,
  `course_description` TEXT NOT NULL DEFAULT '',
  `course_visibility` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`course_id`),
  UNIQUE INDEX `courses_courseid_uindex` (`course_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 154
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fbs`.`submission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fbs`.`submission` ;

CREATE TABLE IF NOT EXISTS `fbs`.`submission` (
  `submission_id` INT NOT NULL AUTO_INCREMENT,
  `file_name` VARCHAR(255) NOT NULL,
  `submission_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `exitcode` INT NOT NULL DEFAULT 1,
  `result_text` TEXT NOT NULL DEFAULT '',
  `checked` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Checker has checked this submission',
  PRIMARY KEY (`submission_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fbs`.`course_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fbs`.`course_role` ;

CREATE TABLE IF NOT EXISTS `fbs`.`course_role` (
  `course_role_id` INT NOT NULL,
  `role_name` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `role_description` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`course_role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `fbs`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fbs`.`task` ;

CREATE TABLE IF NOT EXISTS `fbs`.`task` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `task_name` VARCHAR(200) NOT NULL,
  `task_description` TEXT NOT NULL DEFAULT '',
  `course_id` INT NOT NULL,
  `deadline` DATETIME NOT NULL,
  PRIMARY KEY (`task_id`),
  INDEX `task_courses_courseid_fk` (`course_id` ASC) VISIBLE,
  CONSTRAINT `task_course_course_id_fk`
    FOREIGN KEY (`course_id`)
    REFERENCES `fbs`.`course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 327
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fbs`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fbs`.`user` ;

CREATE TABLE IF NOT EXISTS `fbs`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `prename` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(200) NOT NULL,
  `privacy_checked` TINYINT(1) NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `alias` VARCHAR(20) NULL DEFAULT NULL,
  `global_role` INT NOT NULL DEFAULT 2 COMMENT '0 Admin 1 Moderator 2 User',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 788
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fbs`.`user_task_submission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fbs`.`user_task_submission` ;

CREATE TABLE IF NOT EXISTS `fbs`.`user_task_submission` (
  `submission_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `task_id` INT NULL DEFAULT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `submission_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `exitcode` INT NOT NULL DEFAULT 1,
  `result_text` TEXT NOT NULL DEFAULT '',
  `checked` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Checker has checked this submission',
  PRIMARY KEY (`submission_id`),
  INDEX `submission_task_taskid_fk` (`task_id` ASC) VISIBLE,
  INDEX `submission_users_userid_fk` (`user_id` ASC) VISIBLE,
  CONSTRAINT `submission_task_taskid_fk`
    FOREIGN KEY (`task_id`)
    REFERENCES `fbs`.`task` (`task_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `submission_users_userid_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `fbs`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 19198
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fbs`.`user_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fbs`.`user_course` ;

CREATE TABLE IF NOT EXISTS `fbs`.`user_course` (
  `course_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `course_role_id` INT NOT NULL,
  PRIMARY KEY (`course_id`, `user_id`),
  INDEX `user_has_courses_users_user_id_fk` (`user_id` ASC) VISIBLE,
  INDEX `user_course_role_role_id_fk` (`course_role_id` ASC) VISIBLE,
  CONSTRAINT `user_course_course_course_id_fk`
    FOREIGN KEY (`course_id`)
    REFERENCES `fbs`.`course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_course_role_role_id_fk`
    FOREIGN KEY (`course_role_id`)
    REFERENCES `fbs`.`course_role` (`course_role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_has_courses_users_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `fbs`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fbs`.`checkrunner_configuration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fbs`.`checkrunner_configuration` ;

CREATE TABLE IF NOT EXISTS `fbs`.`checkrunner_configuration` (
  `configuration_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `checker_type` VARCHAR(100) NOT NULL,
  `main_file` VARCHAR(255) NOT NULL,
  `secondary_file` VARCHAR(255) NULL DEFAULT NULL,
  `ord` INT NOT NULL,
  PRIMARY KEY (`configuration_id`),
  INDEX `task_id_idx` (`task_id` ASC) VISIBLE,
  CONSTRAINT `task_id`
    FOREIGN KEY (`task_id`)
    REFERENCES `fbs`.`task` (`task_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
