name: "Retry codecov"
description: "Run codecov and retry on failure"
inputs:
  files:
    description: "Files to upload"
    required: true
  flags:
    description: "Flags to upload"
    required: true
runs:
  using: "composite"
  steps:
    - uses: codecov/codecov-action@v3
      name: Upload Coverage Report
      id: codecov
      with:
        files: ${{ inputs.files }}
        flags: ${{ inputs.flags }}
        fail_ci_if_error: true
    - run: sleep 15s
      shell: bash
      id: sleep-2
      if: always() && steps.codecov.conclusion == 'failure'
    - uses: codecov/codecov-action@v3
      name: Upload Coverage Report (Retry 1)
      id: codecov-1
      if: always() && steps.test.conclusion == 'failure'
      with:
        files: ${{ inputs.files }}
        flags: ${{ inputs.flags }}
        fail_ci_if_error: true
    - run: sleep 15s
      shell: bash
      id: sleep-2
      if: always() && steps.codecov-1.conclusion == 'failure'
    - uses: codecov/codecov-action@v3
      name: Upload Coverage Report (Retry 2)
      id: codecov-2
      if: always() && steps.test.conclusion == 'failure'
      with:
        files: ${{ inputs.files }}
        flags: ${{ inputs.flags }}
        fail_ci_if_error: true
