spring:
  application:
    name: identity-demo
  graphql:
    graphiql:
      enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URI:jdbc:mysql://localhost:3306}/fbs?autoReconnect=true&failOverReadOnly=false&maxReconnects=9&useSSL=false&allowMultiQueries=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:twRuvi2ejllDdA4nnQLa08O}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
    saml2:
      relyingparty:
        registration:
          keycloak:
            entity-id: http://localhost:8080/saml2/metadata/keycloak
            assertingparty:
              metadata-uri: http://localhost:8090/realms/fbs/protocol/saml/descriptor
              singlesignon:
                sign-request: false


app:
  jwt:
    secret: ${JWT_SECRET:q/wBOsfT0wROMO8Uw7rTf+VVvgGczWhkoJSDcaqqPpk=}
    expires-in: ${JWT_EXPIRES_IN:3600}

  saml:
    enabled: false
    registration-id: keycloak
    principal-attribute: uid
    prename-attribute: givenName
    surname-attribute: sn
    email-attribute: mail
    success-url: /login
    failure-url: /login?ssoError=1