app:
  frontend:
    base-url: https://localhost
  saml:
    enabled: true
    registration-id: keycloak
    principal-attribute: uid
    prename-attribute: givenName
    surname-attribute: sn
    email-attribute: mail
    success-path: /login
    failure-path: /login?ssoError=1
    jwt-cookie-name: jwt
    jwt-cookie-max-age-seconds: 30

spring:
  security:
    saml2:
      relyingparty:
        registration:
          keycloak:
            entity-id: http://localhost:8080/saml2/metadata/keycloak
            assertingparty:
              metadata-uri: http://localhost:8090/realms/fbs/protocol/saml/descriptor
              singlesignon:
                sign-request: false
