from enum import Enum


class Datatype(Enum):
    id = "ID"
    street = "Straße"
    product = "Produkt"
    house_number = "Hausnummer"
    company = "Unternehmen"
    email = "Email"
    job = "Arbeit"
    country = "Land"
    lastname = "Nachname"
    firstname = "Vorname"
    address = "Adresse"
    birthdate = "Geburtstag"
    plz = "PLZ"
    city = "Ortsname"
    salary = "50.000-250.000"
    date = "Datum"
    dept = "Abteilung"
    randinteger = "Zufällige Zahl"
    randfloat = "Zufällige Kommazahl"
    category = "Kategorie"
    small_number = "1-10"
    medium_small = "1-100"
    medium = "1-1.000"
    very_large = "100.000-1.000.000"
    medium_large = "10.000-100.000"
    medium_medium = "1-10.000"
    humungous = "100.000-2.500.000"
