name: Add Issue to project
on:
  issues:
    types:
      - opened
jobs:
  add_issue_to_project:
    environment: Project board Automatisation
    name: Add Issue to Project
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.7.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}
      - uses: actions/add-to-project@960fbad431afda394cfcf8743445e741acd19e85
        with:
          project-url: https://github.com/orgs/thm-mni-ii/projects/4
          github-token: ${{ steps.generate_token.outputs.token }}
          labeled: "type: epic"
          label-operator: NOT

      - uses: actions/add-to-project@960fbad431afda394cfcf8743445e741acd19e85
        with:
          project-url: https://github.com/orgs/thm-mni-ii/projects/7
          github-token: ${{ steps.generate_token.outputs.token }}
          labeled: "type: epic"
