name: Check FBS Python Module

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@v3
      - name: Add Problem Matcher
        run: |
          echo "::add-matcher::.github/problem-matchers/python.json"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
      - name: Install library
        run: poetry install --no-interaction  --only dev
      - run: |
          poetry run pylint api
        name: Run Pylint
        continue-on-error: true
      - run: |
          poetry run black --check --diff api
        name: Run Black
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
      - name: Install library
        run: poetry install --no-interaction  --only dev
      - name: Run unittest
        run: poetry run python -m unittest
