name: Check FBS Python Module

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@v4
      - name: Add Problem Matcher
        run: |
          echo "::add-matcher::.github/problem-matchers/python.json"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
      - name: Install library
        run: poetry install --no-interaction
#      - run: |
#          poetry run pylint api --msg-template='${{ inputs.working-directory }}/{path}:{line}:{column}: {msg_id}: {msg} ({symbol})'
#        name: Run Pylint
#        id: pylint
#      - run: |
#          poetry run black --check --verbose --diff api
#        name: Run Black
#        # Run Step even if pylint was not successfull
#        if: ${{ success() || steps.pylint.conclusion == 'failure' }}

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
      - name: Install library
        run: poetry install --no-interaction
      - name: Run unittest
        run: poetry run python -m unittest
