name: CI/CD

on:
  push:
    branches: [dev, main, v*.x]
    tags:
      - v**
  pull_request:

jobs:
  validate-api-docs:
    name: API Docs Validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: swagger-validator
        uses: mbowman100/swagger-validator-action@2.0
        with:
          files: |
            modules/fbs-core/api/api-docs.yml
            modules/fbs-runner/checker/api-docs.yml

  validate-gradle-warpper:
    name: Gradle Warpper Validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@859c33240bd026ce8d5f711f5adcc65c2f8eafc1

  build:
    name: Build Dockerimages
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v3
      - name: Build Dockerimages
        run: bash ./scripts/ci/docker-deploy.sh ${GITHUB_REF##*/}

  deploy:
    name: Build & Deploy Dockerimages to Dockerhub
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    environment:
      name: Docker Hub
      url: https://hub.docker.com/u/thmmniii

    concurrency:
      group: "docker-hub-deploy"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Deploy Dockerimages to Dockerhub
        run: bash ./scripts/ci/docker-deploy.sh ${GITHUB_REF##*/} true

      # TODO: Move to modules
      # - name: Coveralls
      #   run: ./gradlew jacocoRootReport coveralls
      #   env:
      #     CI_NAME: github
      #     COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     COVERALLS_SERVICE_NAME: "github"
      #     CI_PULL_REQUEST: ${{ github.event.number }}
      #     COVERALLS_SERVICE_JOB_ID: ${{ github.run_id }}
