name: CI

on:
  push:
    branches: [dev, main, v*.x]
    tags:
      - v**
  pull_request:

jobs:
  validate-api-docs:
    name: API Docs Validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: swagger-validator
        uses: mbowman100/swagger-validator-action@2.0
        with:
          files: |
            modules/fbs-core/api/api-docs.yml
            modules/fbs-runner/checker/api-docs.yml

  validate-gradle-warpper:
    name: Gradle Warpper Validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@859c33240bd026ce8d5f711f5adcc65c2f8eafc1
  validate-migration:
    name: fbs-core.api / DB Migration Validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check Migration files
        run: bash ./scripts/ci/validate-migrations.sh modules/fbs-core/api/src/main/resources/migrations

  fbs-core-api:
    name: fbs-core.api
    uses: ./.github/workflows/check-fbs-module.yml
    with:
      name: fbs-core.api
      lintArguments: :fbs-core.api:scalastyleCheck
      testArguments: :fbs-core.api:test
      startMysqlService: true

  fbs-core-web:
    name: fbs-core.web
    uses: ./.github/workflows/check-fbs-module.yml
    with:
      name: fbs-core.web
      lintArguments: :fbs-core.web:lint
      testArguments: :fbs-core.web:test

  fbs-runner-checker:
    name: fbs-runner.checker
    uses: ./.github/workflows/check-fbs-module.yml
    with:
      name: fbs-runner.checker
      lintArguments: :fbs-runner.checker:scalastyleCheck
      testArguments: :fbs-runner.checker:test

  build:
    name: Build Docker images
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker images
        run: docker-compose build

      # TODO: Move to modules
      # - name: Coveralls
      #   run: ./gradlew jacocoRootReport coveralls
      #   env:
      #     CI_NAME: github
      #     COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     COVERALLS_SERVICE_NAME: "github"
      #     CI_PULL_REQUEST: ${{ github.event.number }}
      #     COVERALLS_SERVICE_JOB_ID: ${{ github.run_id }}
