name: CI

on:
  push:
    branches: [ dev, main, v*.x ]
    tags:
      - v**
  pull_request:

jobs:
  validate-api-docs:
    name: API Docs Validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.8.1
        if: ${{ inputs.setupNode }}
        with:
          node-version: "16.13.1"
      - name: Add Problem Matcher
        run: echo "::add-matcher::.github/problem-matchers/validate-api-docs.json"
      - run: bash ./scripts/ci/validate-api-docs/validate-api-docs.sh

  validate-gradle-wrapper:
    name: Gradle Wrapper Validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4
  validate-migration:
    name: fbs-core.api / DB Migration Validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check Migration files
        run: bash ./scripts/ci/validate-migrations.sh modules/fbs-core/api/src/main/resources/migrations

  fbs-core-api:
    name: fbs-core.api
    uses: ./.github/workflows/check-fbs-module.yml
    needs: [ "validate-gradle-wrapper", "validate-migration" ]
    with:
      name: fbs-core.api
      lintArguments: :fbs-core.api:scalastyleCheck :fbs-core.api:ktlintCheck :fbs-core.math-parser:ktlintCheck
      testArguments: :fbs-core.api:test :fbs-core.math-parser:test
      coverageArguments: :fbs-core.api:jacocoReport :fbs-core.math-parser:jacocoReport
      coverageFilesLocation: modules/fbs-core/api/build/reports/jacoco/jacocoReport/jacocoReport.xml,modules/fbs-core/math-parser/build/reports/jacoco/jacocoReport/jacocoReport.xml
      startMysqlService: true
      startMinioService: true
      problemMatcher: java.json,kotlin.json

  fbs-core-web:
    name: fbs-core.web
    uses: ./.github/workflows/check-fbs-module.yml
    needs: [ "validate-gradle-wrapper" ]
    with:
      name: fbs-core.web
      lintArguments: :fbs-core.web:lint
      testArguments: :fbs-core.web:build
      setupNode: true

  fbs-runner-checker:
    name: fbs-runner.checker
    uses: ./.github/workflows/check-fbs-module.yml
    needs: [ "validate-gradle-wrapper" ]
    with:
      name: fbs-runner.checker
      lintArguments: :fbs-runner.checker:scalastyleCheck
      testArguments: :fbs-runner.checker:test
      coverageArguments: :fbs-runner.checker:jacocoReport
      coverageFilesLocation: modules/fbs-runner/checker/build/reports/jacoco/jacocoReport/jacocoReport.xml
      problemMatcher: java.json

  fbs-sql-checker:
    name: fbs-sql-checker
    uses: ./.github/workflows/check-fbs-python-module.yml
    with:
      working-directory: ./modules/fbs-sql-checker

  fbs-eat:
    name: fbs-eat
    uses: ./.github/workflows/check-fbs-python-module.yml
    with:
      working-directory: ./modules/fbs-eat/eat

  build:
    name: Build Docker images
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [ "validate-gradle-wrapper", "validate-migration" ]

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker images
        run: docker-compose build
