name: Deploy to GHCR

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main, dev, "v**"]
    types: [completed]

jobs:
  deploy:
    name: Deploy Docker images to GHCR
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      packages: write

    concurrency:
      group: "ghcr-deploy-${{ github.event.workflow_run.head_branch }}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v7
        with:
          # use Previous Workflow ref
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Docker images to GHCR
        env:
          REGISTRY_OWNER: ${{ github.repository_owner }}
        run: bash ./scripts/ci/docker-deploy.sh ${{ github.event.workflow_run.head_branch }} true
