name: Deploy to testsystem

on:
  workflow_run:
    workflows: ["CI/CD"]
    branches: [main, dev, "v**"]
    types: [completed]

jobs:
  deploy:
    name: Deploy to testsystem
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Redeploy testsystem via ssh.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          proxy_host: ${{ secrets.DEPLOY_PROXY_HOST }}
          proxy_username: ${{ secrets.DEPLOY_PROXY_USER }}
          proxy_key: ${{ secrets.DEPLOY_PROXY_KEY }}
          script: deployment/restart-feedbacksystem.sh
