name: fbs-core.api

on:
  push:
    branches: [dev, main, v*.x]
    tags:
      - v**
  pull_request:

jobs:
  validate-migration:
    name: DB Migration Validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check Migration files
        run: bash ./scripts/ci/validate-migrations.sh modules/fbs-core/api/src/main/resources/migrations
  lint:
    name: Lint
    uses: ./.github/workflows/run-gradle-task.yml
    with:
      arguments: :fbs-core.api:scalastyleCheck
  test:
    name: Test
    uses: ./.github/workflows/run-gradle-task.yml
    with:
      arguments: :fbs-core.api:test
      startMysqlService: true
