name: Pages

on:
  push:
    branches: [ dev ]
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  pages:
    name: Publish API Docs
    runs-on: ubuntu-latest
    environment:
      name: api-docs
      url: ${{ steps.deployment.outputs.page_url }}api-docs/
    steps:
      - uses: actions/checkout@v4
      - name: Build Pages
        run: |
          mkdir -p pages/api-docs/runner
          npx redoc-cli bundle modules/fbs-core/api/api-docs.yml 
          mv redoc-static.html pages/api-docs/index.html
          npx redoc-cli bundle modules/fbs-runner/checker/api-docs.yml
          mv redoc-static.html pages/api-docs/runner/index.html
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./pages"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
