name: Playwright Tests with Allure Reports
on:
  push:
    branches: [ dev]
  pull_request:
    branches: [ dev ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Clean previous Allure results
      run: |
        rm -rf allure-results
        rm -rf allure-report
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Install Allure dependencies
      run: npm i -D allure-playwright
    - name: Run Playwright tests with Allure
      run: |
        working-directory: ./modules/fbs-core/web
        export PW_ALLURE_RESULTS_DIR=allure-results
        npx playwright test --reporter=line,allure-playwright
    - name: Generate Allure Report
      run: |
        npx allure generate allure-results --clean -o allure-report
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
          name: allure-report
          path: allure-report/
          retention-days: 30