name: Playwright Tests with Allure Reports
on:
  push:
    branches: [ dev]
  pull_request:
    branches: [ dev ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install Docker Compose
      run: sudo apt-get install -y docker-compose
    - name: Set up Docker environment
      run: |
        cd feedbacksystem
        docker-compose up -d --build
        cd modules/fbs-core/web
        npm install
    - name: Verify local environment
      run: |
          cd modules/fbs-core/web
          npm run start &
          sleep 10
          curl -s http://localhost:4200 || exit 1
    - name: Clean previous Allure results
      run: |
        rm -rf allure-results
        rm -rf allure-report
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Install Allure dependencies
      run: npm i -D allure-playwright
    - name: Run Playwright tests with Allure
      working-directory: ./modules/fbs-core/web
      run: |
        export PW_ALLURE_RESULTS_DIR=allure-results
        npx playwright test ./tests --reporter=line,allure-playwright
    - name: Generate Allure Report
      run: |
        npx allure generate allure-results --clean -o allure-report
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
          name: allure-report
          path: allure-report/
          retention-days: 30