name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release version"
        required: true
        type: string
concurrency:
  group: "release-${{ inputs.version }}"
  cancel-in-progress: true
jobs:
  pages:
    name: Publish release
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - run: echo ${{ inputs.version }}
