name: Run Gradle Task

on:
  workflow_call:
    inputs:
      arguments:
        required: true
        type: string
      startMysqlService:
        required: false
        type: boolean
        default: false

jobs:
  setup-gradle:
    runs-on: ubuntu-latest

    steps:
      - name: Start mysql service container
        if: ${{ inputs.startMysqlService }}
        run: >
          docker run -d --rm --name mysql -e MYSQL_ROOT_PASSWORD=twRuvi2ejllDdA4nnQLa08O
          -e MYSQL_DATABASE=fbs -p 127.0.0.1:3306:3306 mysql:8.0.30
          --default-authentication-plugin=mysql_native_password --sql_mode=""
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ inputs.arguments }}
      - name: Stop mysql service container
        if: ${{ inputs.startMysqlService }}
        run: docker stop mysql
